services:
  app:
    image: ghcr.io/cannoi/password-manager-1kh9:356f752ba4a8d0f241ad152d2d4b932d5adec5d8
    restart: unless-stopped
    labels:
      pi.ui.primary: "true"
    ports:
      - "127.0.0.1:18239:8080"
    environment:
      - PORT=8080
